

import { TeacherData, Student, TeachingJournal, TeacherAgenda, AttitudeRecord, HomeroomRecord, GradeRecord, TeachingMaterial, TeacherLeave, AppSettings } from './types';

export const CLASSES = ['VII A', 'VII B', 'VII C', 'VIII A', 'VIII B', 'VIII C', 'IX A', 'IX B', 'IX C'];

export const COLOR_PALETTE = [
  'bg-red-100 border-red-200 text-red-700',
  'bg-orange-100 border-orange-200 text-orange-700',
  'bg-amber-100 border-amber-200 text-amber-700',
  'bg-yellow-100 border-yellow-200 text-yellow-700',
  'bg-lime-100 border-lime-200 text-lime-700',
  'bg-green-100 border-green-200 text-green-700',
  'bg-emerald-100 border-emerald-200 text-emerald-700',
  'bg-teal-100 border-teal-200 text-teal-700',
  'bg-cyan-100 border-cyan-200 text-cyan-700',
  'bg-sky-100 border-sky-200 text-sky-700',
  'bg-blue-100 border-blue-200 text-blue-700',
  'bg-indigo-100 border-indigo-200 text-indigo-700',
  'bg-violet-100 border-violet-200 text-violet-700',
  'bg-purple-100 border-purple-200 text-purple-700',
  'bg-fuchsia-100 border-fuchsia-200 text-fuchsia-700',
  'bg-pink-100 border-pink-200 text-pink-700',
  'bg-rose-100 border-rose-200 text-rose-700',
  'bg-stone-100 border-stone-200 text-stone-700',
  'bg-blue-50 border-blue-200 text-blue-900',
  'bg-red-50 border-red-200 text-red-900',
];

export const INITIAL_APP_SETTINGS: AppSettings = {
  academicYear: "2025/2026",
  headmaster: "Didik Sulistyo, M.M.Pd",
  headmasterNip: "196605181989011002",
  lastUpdated: "22 Januari 2026",
  logoUrl: "https://image2url.com/r2/default/images/1769001049680-d981c280-6340-4989-8563-7b08134c189a.png",
  semester: "Genap"
};

export const TEACHER_DATA: TeacherData[] = [
  {
    "additionalHours": 4,
    "additionalTask": "Wali Kelas IX B, Guru Wali",
    "code": "BIN-SH",
    "gol": "III d",
    "hoursIX": { "A": 6, "B": 6, "C": 6 },
    "hoursVII": { "A": 0, "B": 0, "C": 0 },
    "hoursVIII": { "A": 0, "B": 0, "C": 6 },
    "id": 1,
    "name": "Dra. Sri Hayati",
    "nip": "196702041992022006",
    "no": "1",
    "rank": "Penata Tk. I",
    "subject": "Bahasa Indonesia",
    "totalHours": 28
  },
  {
    "additionalHours": 14,
    "additionalTask": "Kepala Laboratorium, Guru Wali",
    "code": "IPS-BR",
    "gol": "III d",
    "hoursIX": { "A": 0, "B": 0, "C": 0 },
    "hoursVII": { "A": 0, "B": 0, "C": 0 },
    "hoursVIII": { "A": 4, "B": 4, "C": 4 },
    "id": 2,
    "name": "Bakhtiar Rifai, SE",
    "nip": "196610011993031009",
    "no": "2",
    "rank": "Penata Tk. I",
    "subject": "Ilmu Pengetahuan Sosial",
    "totalHours": 26
  },
  {
    "additionalHours": 4,
    "additionalTask": "Guru Wali, Wali Kelas IX A",
    "code": "PJOK-MH",
    "gol": "III b",
    "hoursIX": { "A": 3, "B": 3, "C": 3 },
    "hoursVII": { "A": 3, "B": 3, "C": 3 },
    "hoursVIII": { "A": 3, "B": 3, "C": 3 },
    "id": 3,
    "name": "Moch. Husain Rifai Hamzah, S.Pd.",
    "nip": "197504112008011011",
    "no": "3",
    "rank": "Penata Muda Tk I",
    "subject": "Penjas Orkes",
    "totalHours": 31
  },
  {
    "additionalHours": 2,
    "additionalTask": "Guru Wali",
    "code": "PAI-RH",
    "gol": "III b",
    "hoursIX": { "A": 3, "B": 3, "C": 3 },
    "hoursVII": { "A": 3, "B": 3, "C": 3 },
    "hoursVIII": { "A": 3, "B": 3, "C": 3 },
    "id": 4,
    "name": "Rudi Hermawan, S.Pd.I",
    "nip": "198910292020121003",
    "no": "4",
    "rank": "Penata Muda",
    "subject": "Pendidikan Agama Islam",
    "totalHours": 29
  },
  {
    "additionalHours": 4,
    "additionalTask": "Wali Kelas VII C, Guru Wali",
    "code": "BK-OD",
    "gol": "III a",
    "hoursIX": { "A": 1, "B": 1, "C": 1 },
    "hoursVII": { "A": 1, "B": 1, "C": 1 },
    "hoursVIII": { "A": 0, "B": 0, "C": 0 },
    "id": 5,
    "name": "Okha Devi Anggraini, S.Pd.",
    "nip": "199610232024212008",
    "no": "5",
    "rank": "Penata Muda",
    "subject": "Bimbingan Konseling",
    "totalHours": 10
  },
  {
    "additionalHours": 4,
    "additionalTask": "Wali Kelas VIII B, Guru Wali",
    "code": "PKN-EH",
    "gol": "IX",
    "hoursIX": { "A": 3, "B": 3, "C": 3 },
    "hoursVII": { "A": 3, "B": 3, "C": 3 },
    "hoursVIII": { "A": 3, "B": 3, "C": 3 },
    "id": 6,
    "name": "Eka Hariyati, S. Pd.",
    "nip": "199212172024212003",
    "no": "6",
    "rank": "Ahli Pertama",
    "subject": "PPKn",
    "totalHours": 31
  },
  {
    "additionalHours": 14,
    "additionalTask": "Wakasek, Guru Wali",
    "code": "BK-MW",
    "gol": "IX",
    "hoursIX": { "A": 0, "B": 0, "C": 0 },
    "hoursVII": { "A": 0, "B": 0, "C": 0 },
    "hoursVIII": { "A": 1, "B": 1, "C": 1 },
    "id": 7,
    "name": "Mikoe Wahyudi Putra, ST., S. Pd.",
    "nip": "198506012024211004",
    "no": "7",
    "rank": "Ahli Pertama",
    "subject": "Bimbingan Konseling",
    "totalHours": 17
  },
  {
    "additionalHours": 4,
    "additionalTask": "Wali Kelas IX C, Guru Wali",
    "code": "MAT-PU",
    "gol": "IX",
    "hoursIX": { "A": 5, "B": 5, "C": 5 },
    "hoursVII": { "A": 0, "B": 0, "C": 0 },
    "hoursVIII": { "A": 0, "B": 5, "C": 5 },
    "id": 8,
    "name": "Purnadi, S. Pd.",
    "nip": "199606192024211001",
    "no": "8",
    "rank": "Ahli Pertama",
    "subject": "Matematika",
    "totalHours": 29
  },
  {
    "additionalHours": 4,
    "additionalTask": "Wali Kelas VII A, Guru Wali",
    "code": "IPS-MU",
    "gol": "IX",
    "hoursIX": { "A": 4, "B": 4, "C": 4 },
    "hoursVII": { "A": 4, "B": 4, "C": 4 },
    "hoursVIII": { "A": 0, "B": 0, "C": 0 },
    "id": 9,
    "name": "Israfin Maria Ulfa, S.Pd",
    "nip": "199612212024212004",
    "no": "9",
    "rank": "Ahli Pertama",
    "subject": "Ilmu Pengetahuan Sosial",
    "totalHours": 28
  },
  {
    "additionalHours": 4,
    "additionalTask": "Wali Kelas VIII A, Guru Wali",
    "code": "BAJA-SB",
    "gol": "",
    "hoursIX": { "A": 2, "B": 2, "C": 2 },
    "hoursVII": { "A": 2, "B": 2, "C": 2 },
    "hoursVIII": { "A": 2, "B": 2, "C": 2 },
    "id": 10,
    "name": "Syadam Budi Satrianto, S.Pd",
    "nip": "-",
    "no": "10",
    "rank": "GTT",
    "subject": "Bahasa Jawa",
    "totalHours": 22
  },
  {
    "additionalHours": 4,
    "additionalTask": "Wali Kelas VII B, Guru Wali",
    "code": "IPA-RB",
    "gol": "",
    "hoursIX": { "A": 5, "B": 5, "C": 5 },
    "hoursVII": { "A": 5, "B": 5, "C": 0 },
    "hoursVIII": { "A": 0, "B": 0, "C": 0 },
    "id": 11,
    "name": "Rebby Dwi Prataopu, S.Si",
    "nip": "-",
    "no": "11",
    "rank": "GTT",
    "subject": "Ilmu Pengetahuan Alam",
    "totalHours": 29
  },
  {
    "additionalHours": 2,
    "additionalTask": "Wali Kelas VII A, Guru Wali",
    "code": "IPA-MY",
    "gol": "",
    "hoursIX": { "A": 0, "B": 0, "C": 0 },
    "hoursVII": { "A": 0, "B": 0, "C": 5 },
    "hoursVIII": { "A": 5, "B": 5, "C": 5 },
    "id": 12,
    "name": "Mukhamad Yunus, S.Pd",
    "nip": "-",
    "no": "12",
    "rank": "GTT",
    "subject": "Ilmu Pengetahuan Alam",
    "totalHours": 22
  },
  {
    "additionalHours": 0,
    "additionalTask": "-",
    "code": "INF-MY",
    "gol": "",
    "hoursIX": { "A": 0, "B": 0, "C": 0 },
    "hoursVII": { "A": 0, "B": 0, "C": 0 },
    "hoursVIII": { "A": 3, "B": 3, "C": 0 },
    "id": 1201,
    "name": "Mukhamad Yunus, S.Pd",
    "nip": "-",
    "no": "",
    "rank": "-",
    "subject": "Informatika",
    "totalHours": 6
  },
  {
    "additionalHours": 2,
    "additionalTask": "Guru Wali",
    "code": "BIN-FW",
    "gol": "",
    "hoursIX": { "A": 0, "B": 0, "C": 0 },
    "hoursVII": { "A": 6, "B": 6, "C": 6 },
    "hoursVIII": { "A": 6, "B": 6, "C": 0 },
    "id": 13,
    "name": "Fahmi Wahyuni, S.Pd",
    "nip": "-",
    "no": "13",
    "rank": "GTT",
    "subject": "Bahasa Indonesia",
    "totalHours": 32
  },
  {
    "additionalHours": 2,
    "additionalTask": "Guru Wali",
    "code": "SENI-FA",
    "gol": "",
    "hoursIX": { "A": 2, "B": 2, "C": 2 },
    "hoursVII": { "A": 2, "B": 2, "C": 2 },
    "hoursVIII": { "A": 2, "B": 2, "C": 2 },
    "id": 14,
    "name": "Fakhita Madury, S.Sn",
    "nip": "-",
    "no": "14",
    "rank": "GTT",
    "subject": "Seni (Seni Rupa)",
    "totalHours": 20
  },
  {
    "additionalHours": 0,
    "additionalTask": "-",
    "code": "INF-FA",
    "gol": "",
    "hoursIX": { "A": 0, "B": 0, "C": 0 },
    "hoursVII": { "A": 3, "B": 3, "C": 3 },
    "hoursVIII": { "A": 0, "B": 0, "C": 0 },
    "id": 1401,
    "name": "Fakhita Madury, S.Sn",
    "nip": "-",
    "no": "",
    "rank": "GTT",
    "subject": "Informatika",
    "totalHours": 9
  },
  {
    "additionalHours": 4,
    "additionalTask": "Wali Kelas VIII C, Guru Wali",
    "code": "BIG-RN",
    "gol": "IX",
    "hoursIX": { "A": 4, "B": 4, "C": 4 },
    "hoursVII": { "A": 0, "B": 0, "C": 0 },
    "hoursVIII": { "A": 4, "B": 4, "C": 4 },
    "id": 15,
    "name": "Retno Nawangwulan, S. Pd.",
    "nip": "-",
    "no": "15",
    "rank": "Ahli Pertama",
    "subject": "Bahasa Inggris",
    "totalHours": 28
  },
  {
    "additionalHours": 2,
    "additionalTask": "Guru Wali",
    "code": "MAT-EM",
    "gol": "IX",
    "hoursIX": { "A": 0, "B": 0, "C": 0 },
    "hoursVII": { "A": 5, "B": 5, "C": 5 },
    "hoursVIII": { "A": 5, "B": 0, "C": 0 },
    "id": 16,
    "name": "Emilia Kartika Sari, S.Pd",
    "nip": "-",
    "no": "16",
    "rank": "Ahli Pertama",
    "subject": "Matematika",
    "totalHours": 22
  },
  {
    "additionalHours": 0,
    "additionalTask": "-",
    "code": "INF-EM",
    "gol": "IX",
    "hoursIX": { "A": 3, "B": 0, "C": 0 },
    "hoursVII": { "A": 0, "B": 0, "C": 0 },
    "hoursVIII": { "A": 0, "B": 0, "C": 3 },
    "id": 1601,
    "name": "Emilia Kartika Sari, S.Pd",
    "nip": "-",
    "no": "",
    "rank": "Ahli Pertama",
    "subject": "Informatika",
    "totalHours": 6
  },
  {
    "additionalHours": 14,
    "additionalTask": "Kepala Perpustakaan, Guru Wali",
    "code": "BIG-AH",
    "gol": "III b",
    "hoursIX": { "A": 0, "B": 0, "C": 0 },
    "hoursVII": { "A": 4, "B": 4, "C": 4 },
    "hoursVIII": { "A": 0, "B": 0, "C": 0 },
    "id": 17,
    "name": "Akhmad Hariadi, S.Pd",
    "nip": "197201011999031001",
    "no": "17",
    "rank": "Penata Muda Tk I",
    "subject": "Bahasa Inggris",
    "totalHours": 26
  },
  {
    "additionalHours": 0,
    "additionalTask": "-",
    "code": "INF-AH",
    "gol": "III b",
    "hoursIX": { "A": 0, "B": 3, "C": 3 },
    "hoursVII": { "A": 0, "B": 0, "C": 0 },
    "hoursVIII": { "A": 0, "B": 0, "C": 0 },
    "id": 1701,
    "name": "Akhmad Hariadi, S.Pd",
    "nip": "197201011999031001",
    "no": "",
    "rank": "Penata Muda Tk I",
    "subject": "Informatika",
    "totalHours": 6
  }
];

export const INITIAL_STUDENTS: Student[] = [
  { "className": "VII A", "id": "1", "name": "ACSELIN UKE DWINANTA" },
  { "className": "VII A", "id": "2", "name": "AHMAD DWI NAVI SAPUTRA" },
  { "className": "VII A", "id": "3", "name": "AKIRA MUMTAZA GHULAM MAHRON" },
  { "className": "VII A", "id": "4", "name": "ANGGITAH MAHARANI" },
  { "className": "VII A", "id": "5", "name": "ARIMBI AUNI MAYANGSARI" },
  { "className": "VII A", "id": "6", "name": "ARSY TIRTASYA PRAYOGI ISBIANTO" },
  { "className": "VII A", "id": "7", "name": "DEFIANA NUR RAHMA" },
  { "className": "VII A", "id": "8", "name": "DINDA RESTYNING RAHAYU" },
  { "className": "VII A", "id": "9", "name": "IRKHAM ARTHUR MAULANA" },
  { "className": "VII A", "id": "10", "name": "KADITA NATHANIA" },
  { "className": "VII A", "id": "11", "name": "MOHAMMAD ROFIQ ARDIANSYAH" },
  { "className": "VII A", "id": "12", "name": "MUHAMMAD AZZAM NUR ALIF" },
  { "className": "VII A", "id": "13", "name": "MUHAMMAD ARDITIYO SEBASTIAN" },
  { "className": "VII A", "id": "14", "name": "MUHAMMAD EZZAR ALI YUDHA" },
  { "className": "VII A", "id": "15", "name": "MUHAMMAD FAIZ QISBIY ROMADHONI" },
  { "className": "VII A", "id": "16", "name": "OLIVIA ADELLA NAZAHRA" },
  { "className": "VII A", "id": "17", "name": "QOTRUNNADA SALSABILA AKMAL" },
  { "className": "VII A", "id": "18", "name": "RAMA SULTHAN AULIYA AHMAD" },
  { "className": "VII A", "id": "19", "name": "REFAN AZZAM ANUGRAH" },
  { "className": "VII A", "id": "20", "name": "SEPTIA INDAH WULANDARI" },
  { "className": "VII A", "id": "21", "name": "SOEGIARTO WIJAYA" },
  { "className": "VII A", "id": "22", "name": "STEFANI ANANDA RAHMADHANI" },
  { "className": "VII A", "id": "23", "name": "VIRDY PUTRI HARUM KUSUMA" },
  { "className": "VII A", "id": "24", "name": "ZAINI ALI MAHMUD" },
  { "className": "VII A", "id": "25", "name": "ZAVERIO AMSYAR RAFFASYA" },
  { "className": "VII B", "id": "26", "name": "ACHMAD FATAH ADI DARMA" },
  { "className": "VII B", "id": "27", "name": "ARGA ARDIANSA" },
  { "className": "VII B", "id": "28", "name": "AVYKA VERA JUNYARTHA" },
  { "className": "VII B", "id": "29", "name": "DENIS ANGGORO" },
  { "className": "VII B", "id": "30", "name": "DIRLY MICHELE FEBRYAN SUSANTO" },
  { "className": "VII B", "id": "31", "name": "DWI ANDIKA PUTRA SETIAWAN" },
  { "className": "VII B", "id": "32", "name": "FEMILYA QONITA ARINIL HAQ" },
  { "className": "VII B", "id": "33", "name": "HIKMATUL MEISYAH ANJANI" },
  { "className": "VII B", "id": "34", "name": "IQBAL MAULANA AL AZZAM" },
  { "className": "VII B", "id": "35", "name": "KASIH PUTRI SURYA NINGRUM" },
  { "className": "VII B", "id": "36", "name": "KIKI FATMAWATI" },
  { "className": "VII B", "id": "37", "name": "KRIDHO HERVA NATASYA PUTRI" },
  { "className": "VII B", "id": "38", "name": "MOKHAMAD FARA BARIQ SAPUTRA" },
  { "className": "VII B", "id": "39", "name": "MUCHAMMAD ILYAS NUR ADINATA" },
  { "className": "VII B", "id": "40", "name": "MUHAMMAD FARHAN MAULANA" },
  { "className": "VII B", "id": "41", "name": "MUHAMMAD KHOIRUL ANAM" },
  { "className": "VII B", "id": "42", "name": "MUHAMMAD SONIUL ULUMI" },
  { "className": "VII B", "id": "43", "name": "NIZHAR ADITYA ROHMAN" },
  { "className": "VII B", "id": "44", "name": "NUR AINI AGUSTIN" },
  { "className": "VII B", "id": "45", "name": "REVALINA DWI RATNASARI" },
  { "className": "VII B", "id": "46", "name": "SAKA BUANA IKSAN WIJAYANTO" },
  { "className": "VII B", "id": "47", "name": "SYAHRIL FIKRI AMRULLOH" },
  { "className": "VII B", "id": "48", "name": "WAHYU ALIFIANSYAH PUTRA MANGKU B." },
  { "className": "VII B", "id": "49", "name": "WENIDA EKA ANADIA PUTRI" },
  { "className": "VII B", "id": "50", "name": "DZAKIYYA TALITA ZAHRA" },
  { "className": "VII B", "id": "51", "name": "RANIA SYAFA'A PUTRI IMANSYAH" },
  { "className": "VII B", "id": "52", "name": "MOH. DAFFA FAUZAN WIFQULKHOIR" },
  { "className": "VII C", "id": "53", "name": "AISYAH AYU LESTARI" },
  { "className": "VII C", "id": "54", "name": "AISYAH ZANETA SALSABILLA" },
  { "className": "VII C", "id": "55", "name": "ALFARO FEBRIANSYAH WAHYUDI" },
  { "className": "VII C", "id": "56", "name": "APRILIA DWI LESTARI" },
  { "className": "VII C", "id": "57", "name": "CHILYATUZ ZAKIA AINA SALSABILA" },
  { "className": "VII C", "id": "58", "name": "DHAFA SATRIAWAN PRATAMA" },
  { "className": "VII C", "id": "59", "name": "DINDA AKILA PRATIWI" },
  { "className": "VII C", "id": "60", "name": "ELINA ASTRIT YUNEDY" },
  { "className": "VII C", "id": "61", "name": "ENJELINA MIKE ANGGUN LESTARI" },
  { "className": "VII C", "id": "62", "name": "FANI RAHMA ADTYA" },
  { "className": "VII C", "id": "63", "name": "FATALARIK KHAIRUSANI IBNU YAKSHA" },
  { "className": "VII C", "id": "64", "name": "HAIKAL RAYSHA FACHRUDDIN" },
  { "className": "VII C", "id": "65", "name": "HARDIAN SYAHPUTRA" },
  { "className": "VII C", "id": "66", "name": "KIRANA DINAR FADHILLAH QAIS" },
  { "className": "VII C", "id": "67", "name": "JUSTIN GILBERT APRILIO HALIM" },
  { "className": "VII C", "id": "68", "name": "MAULINDA KUSUMA" },
  { "className": "VII C", "id": "69", "name": "MOHAMAD IZAM HAIKAL NAFIS" },
  { "className": "VII C", "id": "70", "name": "MOHAMMAD DAFFA MAULANA AWWALUDDIN" },
  { "className": "VII C", "id": "71", "name": "MUHAMAD DIMAS SAPUTRA" },
  { "className": "VII C", "id": "72", "name": "DWI AZZAHRA RAMADHANI" },
  { "className": "VII C", "id": "73", "name": "MUHAMMAD EZAR NAFIL" },
  { "className": "VII C", "id": "74", "name": "MUHAMMAD FARIS ALFARIZI" },
  { "className": "VII C", "id": "75", "name": "MUHAMMAD NICOLA VERDIANSYAH" },
  { "className": "VII C", "id": "76", "name": "YUWIETA TRI ANGGREINY" },
  { "className": "VII C", "id": "77", "name": "ZAFAR SIDIQ" },
  { "className": "VIII A", "id": "78", "name": "ACHMAD KIESHA RIZQI ANDIKA" },
  { "className": "VIII A", "id": "79", "name": "ALANSKY VANI ARIEFKY PUTRA" },
  { "className": "VIII A", "id": "80", "name": "ALMIRAH YUNITA" },
  { "className": "VIII A", "id": "81", "name": "ANA NAYLA SALSABILLA" },
  { "className": "VIII A", "id": "82", "name": "ARIYA FERDIANSA" },
  { "className": "VIII A", "id": "83", "name": "ASIFA AMELIA PUTRI" },
  { "className": "VIII A", "id": "84", "name": "ASMIAR AFIQOH RACHMADHANI" },
  { "className": "VIII A", "id": "85", "name": "AURA MIFVATUL PUTRI" },
  { "className": "VIII A", "id": "86", "name": "AVELIYAN AGHIL EDDYANZA" },
  { "className": "VIII A", "id": "87", "name": "IMELDA NAJWA AYU KUMALASARI" },
  { "className": "VIII A", "id": "88", "name": "INDRA BAGUS SAPUTRA" },
  { "className": "VIII A", "id": "89", "name": "JESICA APRILIA AYUNENGTIAS" },
  { "className": "VIII A", "id": "90", "name": "MOCH DEVAN SAPUTRA" },
  { "className": "VIII A", "id": "91", "name": "MOHAMMAD DAFFA" },
  { "className": "VIII A", "id": "92", "name": "MUH. REVAN RIZKI PRATAMA" },
  { "className": "VIII A", "id": "93", "name": "MUHAMMAD BAYU SAPUTRO" },
  { "className": "VIII A", "id": "94", "name": "MUHAMMAD NASRUL MUJAQQI" },
  { "className": "VIII A", "id": "95", "name": "MUKHAMAD ILYAS RIZKY ABDILLAH" },
  { "className": "VIII A", "id": "96", "name": "NADZAR PANDU PRAHASTA" },
  { "className": "VIII A", "id": "97", "name": "NAURA CECILYA ANGELYCA" },
  { "className": "VIII A", "id": "98", "name": "NAURAH SALSABILA" },
  { "className": "VIII A", "id": "99", "name": "NAZWA NATASYA PUTRI" },
  { "className": "VIII A", "id": "100", "name": "PUPUT KUMALA SARI" },
  { "className": "VIII A", "id": "101", "name": "PUTRI EKA NILASARI" },
  { "className": "VIII A", "id": "102", "name": "PUTRI JUWITA SARI" },
  { "className": "VIII A", "id": "103", "name": "RAFIQ MAULANA" },
  { "className": "VIII A", "id": "104", "name": "REVAND DWI AL DIANO" },
  { "className": "VIII A", "id": "105", "name": "RIYADHUL BUKHORI" },
  { "className": "VIII A", "id": "106", "name": "KYANO RICKY SAPUTRA" },
  { "className": "VIII A", "id": "107", "name": "SERLIYAH CAHYA FITRIANI" },
  { "className": "VIII A", "id": "108", "name": "SESILLIA ANGELINA PUTRI" },
  { "className": "VIII A", "id": "109", "name": "SHEGA RAMADHANI" },
  { "className": "VIII A", "id": "110", "name": "VALENCIA SELLA FENDY SAFIRA" },
  { "className": "VIII A", "id": "111", "name": "WAHYU NUR AHMAD SETIO BUDI" },
  { "className": "VIII A", "id": "112", "name": "YUSRIEL ADI ALFAREZA" },
  { "className": "VIII B", "id": "113", "name": "ACHMAD DAFFA KURNIAWAN" },
  { "className": "VIII B", "id": "114", "name": "AHMAD RAVA MAULANA" },
  { "className": "VIII B", "id": "115", "name": "AHMAD YONGKY ROFIKUL A'LA" },
  { "className": "VIII B", "id": "116", "name": "AKHMAD RIFKI SAMSUL ANGGORO" },
  { "className": "VIII B", "id": "117", "name": "ALDELIA PUTRI ANNUROH" },
  { "className": "VIII B", "id": "118", "name": "ALIVIA AZZAHRA" },
  { "className": "VIII B", "id": "119", "name": "AMELIA DWI AMANDA SARI" },
  { "className": "VIII B", "id": "120", "name": "BISMA PUTRA RAMADHAN" },
  { "className": "VIII B", "id": "121", "name": "CINTIA ZIFA PERMATA KIRANA" },
  { "className": "VIII B", "id": "122", "name": "DESYIFA ADELIA EKA FIRNANDA" },
  { "className": "VIII B", "id": "123", "name": "DEWI AVIKA PUTRI" },
  { "className": "VIII B", "id": "124", "name": "DWI KANAYA PUTRI" },
  { "className": "VIII B", "id": "125", "name": "FADILLAH AINI KHOMARI" },
  { "className": "VIII B", "id": "126", "name": "IVANDER ZAKI ANGGARA" },
  { "className": "VIII B", "id": "127", "name": "JULIANA PUTRI" },
  { "className": "VIII B", "id": "128", "name": "KELFIN ANDIKA PRATAMA" },
  { "className": "VIII B", "id": "129", "name": "KYANOE LUCKY WIJJAYA" },
  { "className": "VIII B", "id": "130", "name": "LOEIS ADITYA PUTRA" },
  { "className": "VIII B", "id": "131", "name": "MOCHAMAD VICKY WAHYUPI" },
  { "className": "VIII B", "id": "132", "name": "MUHAMAD AYUBI ANAS" },
  { "className": "VIII B", "id": "133", "name": "MUHAMMAD ILHAM SYAFI'I" },
  { "className": "VIII B", "id": "134", "name": "MUHAMMAD RENDI ADITYA" },
  { "className": "VIII B", "id": "135", "name": "MUHAMMAD REZZA SETYAWAN" },
  { "className": "VIII B", "id": "136", "name": "MUHAMMAD YAFIUL HAMZI" },
  { "className": "VIII B", "id": "137", "name": "MUKHAMMAD ARYA MAULANA" },
  { "className": "VIII B", "id": "138", "name": "NARITA SILVIA DEWI" },
  { "className": "VIII B", "id": "139", "name": "NAYLA HIDAYATUN NUFUS" },
  { "className": "VIII B", "id": "140", "name": "OKTAVIAN ERGIANSYAH" },
  { "className": "VIII B", "id": "141", "name": "RIZKI VERANIKA ANDINA SOLIKHAH" },
  { "className": "VIII B", "id": "142", "name": "ROSYIDAH WULANDARI" },
  { "className": "VIII B", "id": "143", "name": "TUNGGUL DIAS ARIANSYAH" },
  { "className": "VIII B", "id": "144", "name": "WILDA PRATIWI" },
  { "className": "VIII B", "id": "145", "name": "WILDHA CHELSEA META OCTAVIA" },
  { "className": "VIII B", "id": "146", "name": "ASTI DWI NATHANIA PUTRI" },
  { "className": "VIII C", "id": "147", "name": "AHMAD ZAIYANI WARDANI" },
  { "className": "VIII C", "id": "148", "name": "ARIEL SENNA DWI FIRMANSYAH" },
  { "className": "VIII C", "id": "149", "name": "AVRILIA EKA RAHMAWATI" },
  { "className": "VIII C", "id": "150", "name": "AYU ANDIRA" },
  { "className": "VIII C", "id": "151", "name": "AZAM IBI SYEVIK" },
  { "className": "VIII C", "id": "152", "name": "AZKA ATALARIC ZACHARI KHALFANI" },
  { "className": "VIII C", "id": "153", "name": "CINTA RAHMA ASIYA" },
  { "className": "VIII C", "id": "154", "name": "DAUD ATHOURROHMAN KAMAL" },
  { "className": "VIII C", "id": "155", "name": "DINI OLIVIA PUTRI" },
  { "className": "VIII C", "id": "156", "name": "DIO ARSYAH MAULANA" },
  { "className": "VIII C", "id": "157", "name": "FERLIN ELSA HAVIVA" },
  { "className": "VIII C", "id": "158", "name": "JANITA KAMILA ZAMAN" },
  { "className": "VIII C", "id": "159", "name": "JESLYN SHAILA LEXIA AMORA" },
  { "className": "VIII C", "id": "160", "name": "KYANNO RENDRA BUDI PRATAMA" },
  { "className": "VIII C", "id": "161", "name": "LUTVI RASYA RAMADHAN" },
  { "className": "VIII C", "id": "162", "name": "MAHFIDHO ZAKIYATUS SHAFA" },
  { "className": "VIII C", "id": "163", "name": "MARCELLINO MAULANA MAZBULLAH" },
  { "className": "VIII C", "id": "164", "name": "MARTHA DWI TARADILA" },
  { "className": "VIII C", "id": "165", "name": "MIFTAKHUL JANAH" },
  { "className": "VIII C", "id": "166", "name": "MOHAMMAD DAVID ALFIANSYAH" },
  { "className": "VIII C", "id": "167", "name": "MUHAMMAD FAIS ILHAM" },
  { "className": "VIII C", "id": "168", "name": "MUHAMMAD IQBAL ALIE MUZAKI" },
  { "className": "VIII C", "id": "169", "name": "MUHAMMAD KHADID ANWARY" },
  { "className": "VIII C", "id": "170", "name": "MUHAMMAD NASYA PRADIPTA OKTAFA" },
  { "className": "VIII C", "id": "171", "name": "MUHAMMAD WAHYU RAMDHANI" },
  { "className": "VIII C", "id": "172", "name": "MUKHAMAT FAHRUL" },
  { "className": "VIII C", "id": "173", "name": "MUKHAMMAD RIZKY WANDIAN SYAH" },
  { "className": "VIII C", "id": "174", "name": "NADYA LOVITA PUTRI" },
  { "className": "VIII C", "id": "175", "name": "NAFISHATUL MUFIDAH" },
  { "className": "VIII C", "id": "176", "name": "NERLITA ADELIA PUTRI" },
  { "className": "VIII C", "id": "177", "name": "NOVALUNA ADINDA PUTRI" },
  { "className": "VIII C", "id": "178", "name": "RENO AIDHIL ELMAWANTO" },
  { "className": "VIII C", "id": "179", "name": "RIYO FAFA ALAMSYAH" },
  { "className": "VIII C", "id": "180", "name": "SILVI ADELLYA ANDINI" },
  { "className": "VIII C", "id": "181", "name": "TEGAR HENDY RISWANTO" },
  { "className": "IX A", "id": "182", "name": "ABEL AULIA PASA RAMADANI" },
  { "className": "IX A", "id": "183", "name": "ADITYA FIRMANSYAH" },
  { "className": "IX A", "id": "184", "name": "AHMAD NIAM IZZI AFKAR" },
  { "className": "IX A", "id": "185", "name": "DAFA RISKI EKA SYAHPUTRA" },
  { "className": "IX A", "id": "186", "name": "DEA NAYLATUL AFITA" },
  { "className": "IX A", "id": "187", "name": "DHEA ZASKIA OLIVIA PUTRI" },
  { "className": "IX A", "id": "188", "name": "ENGGELITA REGINA PUTRI" },
  { "className": "IX A", "id": "189", "name": "FAREL ANDRIANSAH" },
  { "className": "IX A", "id": "190", "name": "FURI ANGELIKA PUTRI" },
  { "className": "IX A", "id": "191", "name": "JESICHA PUTRI RAMADHANI" },
  { "className": "IX A", "id": "192", "name": "JIHAN DEA VALQOHI" },
  { "className": "IX A", "id": "193", "name": "M. FERDY SANTOSO" },
  { "className": "IX A", "id": "194", "name": "MICHELIA ANDARA PUTRI AGUSTINA" },
  { "className": "IX A", "id": "195", "name": "MUHAMAD ADITIYA SUGIHARTO" },
  { "className": "IX A", "id": "196", "name": "MUHAMAD RIFKI AFANDI" },
  { "className": "IX A", "id": "197", "name": "MUHAMMAD AL AMIN" },
  { "className": "IX A", "id": "198", "name": "MUHAMMAD BAHRUDIN NICOLAS SAPUTRA" },
  { "className": "IX A", "id": "199", "name": "MUHAMMAD HAIKAL DWI APRIANSYAH" },
  { "className": "IX A", "id": "200", "name": "MUHAMMAD REHAN MEYLANO" },
  { "className": "IX A", "id": "201", "name": "MUHAMMAD RIZQI FATKUR ROZI" },
  { "className": "IX A", "id": "202", "name": "NABILA SRI WULANDARI" },
  { "className": "IX A", "id": "203", "name": "RIFKI ARDIAN SYAPUTRA" },
  { "className": "IX A", "id": "204", "name": "SALSABILLA PUTRI RAMADHANI" },
  { "className": "IX A", "id": "205", "name": "SASKIA AISYAH AZZAHRA" },
  { "className": "IX A", "id": "206", "name": "SHERLIN HERLA AZZAHRA" },
  { "className": "IX A", "id": "207", "name": "SLAMET RIZKI GALI RIMBA ANGKASA" },
  { "className": "IX A", "id": "208", "name": "VALENSYA DWI PUTRI WIJAYA" },
  { "className": "IX A", "id": "209", "name": "WILDAN DIMAS DWI ANANDA" },
  { "className": "IX A", "id": "210", "name": "DEFANO HAIKAL RAMADHAN" },
  { "className": "IX A", "id": "211", "name": "SAMSUL NURUL HUDA" },
  { "className": "IX B", "id": "212", "name": "ABHEL ECHA TRIOCTAVIA NATASYA" },
  { "className": "IX B", "id": "213", "name": "ADITYA SAPUTRA" },
  { "className": "IX B", "id": "214", "name": "AKBAR KHAFI AS SHAFFAAT" },
  { "className": "IX B", "id": "215", "name": "Alviansyah Radityah Putra" },
  { "className": "IX B", "id": "216", "name": "ANINDITA WIDIYA CAHYANI" },
  { "className": "IX B", "id": "217", "name": "Bayu Widiat Moko" },
  { "className": "IX B", "id": "218", "name": "CANTICA ENGEL AULIA SHAVIRA" },
  { "className": "IX B", "id": "219", "name": "FANIA KHOIROTUL UMMAH" },
  { "className": "IX B", "id": "220", "name": "HANUM PUSPITA SARI" },
  { "className": "IX B", "id": "221", "name": "KEYVIN RAJA DIRHAM" },
  { "className": "IX B", "id": "222", "name": "Kinansye Novita Kreyti" },
  { "className": "IX B", "id": "223", "name": "M. REVA INDRA RAMADHANI" },
  { "className": "IX B", "id": "224", "name": "MOHAMMAD SURYA PUTRA JUANDA" },
  { "className": "IX B", "id": "225", "name": "MUHAMMAD AZZAM AUFA RIZKY" },
  { "className": "IX B", "id": "226", "name": "MUHAMMAD EDO PRATAMA" },
  { "className": "IX B", "id": "227", "name": "MUHAMMAD RIZKI FEBRIAN PRATAMA" },
  { "className": "IX B", "id": "228", "name": "NIHAYATUL HIMMAH" },
  { "className": "IX B", "id": "229", "name": "Ninis Daniyah Permatasari" },
  { "className": "IX B", "id": "230", "name": "PUTUT EKA DWI PRADANA" },
  { "className": "IX B", "id": "231", "name": "RENO ARDIKA FEBRIANSYAH" },
  { "className": "IX B", "id": "232", "name": "REZKY REVAN'A ADITYA" },
  { "className": "IX B", "id": "233", "name": "ROHMATUN NADIYAH" },
  { "className": "IX B", "id": "234", "name": "Siwetul Jennah" },
  { "className": "IX B", "id": "235", "name": "TONI ADI SETIAWAN" },
  { "className": "IX B", "id": "236", "name": "VEHANA RECHA INEZHA" },
  { "className": "IX B", "id": "237", "name": "VISCHA AZZAHRA PUTRI" },
  { "className": "IX B", "id": "238", "name": "WINDA SRI ASTUTIK" },
  { "className": "IX B", "id": "239", "name": "YUSRIL ALFAREL NUGRAHA" },
  { "className": "IX B", "id": "240", "name": "ZIDAN RAHMAT ADITYA" },
  { "className": "IX B", "id": "241", "name": "YUSUF ADITYA ALIN PRATAMA" },
  { "className": "IX C", "id": "242", "name": "ADINDA DWI PRASETYAWAN" },
  { "className": "IX C", "id": "243", "name": "AHKMAD IRCHAM ALI AZKIYA JAZULY" },
  { "className": "IX C", "id": "244", "name": "AKHMAD EGA JULIANO" },
  { "className": "IX C", "id": "245", "name": "AMIRULLOH AKBAR" },
  { "className": "IX C", "id": "246", "name": "ANDIEN DINAR FADHILLAH QAIS" },
  { "className": "IX C", "id": "247", "name": "AULIA PUTRY RAUDIATUL JANNAH" },
  { "className": "IX C", "id": "248", "name": "AURELIA FATIMAH YUNITA" },
  { "className": "IX C", "id": "249", "name": "AYU DEVINA EKA PRATIWI" },
  { "className": "IX C", "id": "250", "name": "BINTANG PRATAMA" },
  { "className": "IX C", "id": "251", "name": "CITRA TRIAN ANDINI" },
  { "className": "IX C", "id": "252", "name": "DENIS EKA FEBRIAN" },
  { "className": "IX C", "id": "253", "name": "ELISA DINDA SAVIERA" },
  { "className": "IX C", "id": "254", "name": "FAJAR ADITYA PUTRA" },
  { "className": "IX C", "id": "255", "name": "GRISELDA SANDRA ADELIA" },
  { "className": "IX C", "id": "256", "name": "JASTINE DIAN DWI ALEXTIAN" },
  { "className": "IX C", "id": "257", "name": "KAFRIDA INDAH DWI PRAMESTI" },
  { "className": "IX C", "id": "258", "name": "KRISNA WAHYU ARIYANSYAH" },
  { "className": "IX C", "id": "259", "name": "MIFTAKHUL DWIYANTI" },
  { "className": "IX C", "id": "260", "name": "MOHKAMAT SLAMET PRASETIO" },
  { "className": "IX C", "id": "261", "name": "MUHAMAD THORIQ SHOLIKHUL ULAH" },
  { "className": "IX C", "id": "262", "name": "MUHAMMAD BAGUS DWI SETIAWAN" },
  { "className": "IX C", "id": "263", "name": "MUHAMMAD SYAHLAN AL FARISI" },
  { "className": "IX C", "id": "264", "name": "MUHAMMAD SYAIFUDDIN ZUHRI" },
  { "className": "IX C", "id": "265", "name": "MUKHAMMAD NAFIS  ZANWAR" },
  { "className": "IX C", "id": "266", "name": "PUTRA FAIZ ABILANSA" },
  { "className": "IX C", "id": "267", "name": "RAKA ZA ARKAN AL YAHYA" },
  { "className": "IX C", "id": "268", "name": "RIZKY DWI PRASETYA" },
  { "className": "IX C", "id": "269", "name": "SAHAZIKA GISTIANO MAISEGALUNG" },
  { "className": "IX C", "id": "270", "name": "ACHMAD SAIFUL ANWAR" }
];

export const SCHEDULE_DATA = [
  {
    day: "SENIN",
    rows: [
      { jam: "0", waktu: "06.30 - 06.45", activity: "Persiapan Upacara Bendera" },
      { jam: "1", waktu: "06.45 - 07.40", activity: "Upacara Bendera" },
      { jam: "2", waktu: "07.40 - 08.20" },
      { jam: "3", waktu: "08.20 - 09.00" },
      { jam: "", waktu: "09.00 - 09.20", activity: "Istirahat ke-1" },
      { jam: "4", waktu: "09.20 - 10.00" },
      { jam: "5", waktu: "10.00 - 10.40" },
      { jam: "6", waktu: "10.40 - 11.20" },
      { jam: "", waktu: "11.20 - 11.50", activity: "Istirahat 2 / Sholat Dzuhur Berjamaah" },
      { jam: "7", waktu: "11.50 - 12.25" },
      { jam: "8", waktu: "12.25 - 13.00" },
    ]
  },
  {
    day: "SELASA",
    rows: [
      { jam: "0", waktu: "06.30 - 07.00", activity: "Apel Pagi / Pembacaan Surat Ar-Rahman" },
      { jam: "1", waktu: "07.00 - 07.40" },
      { jam: "2", waktu: "07.40 - 08.20" },
      { jam: "3", waktu: "08.20 - 09.00" },
      { jam: "", waktu: "09.00 - 09.20", activity: "Istirahat ke-1" },
      { jam: "4", waktu: "09.20 - 10.00" },
      { jam: "5", waktu: "10.00 - 10.40" },
      { jam: "6", waktu: "10.40 - 11.20" },
      { jam: "", waktu: "11.20 - 11.50", activity: "Istirahat 2 / Sholat Dzuhur Berjamaah" },
      { jam: "7", waktu: "11.50 - 12.25" },
      { jam: "8", waktu: "12.25 - 13.00" },
    ]
  },
  {
    day: "RABU",
    rows: [
      { jam: "0", waktu: "06.30 - 07.00", activity: "Apel Pagi / Pembacaan Surat Al Waqi'ah" },
      { jam: "1", waktu: "07.00 - 07.40" },
      { jam: "2", waktu: "07.40 - 08.20" },
      { jam: "3", waktu: "08.20 - 09.00" },
      { jam: "", waktu: "09.00 - 09.20", activity: "Istirahat ke-1" },
      { jam: "4", waktu: "09.20 - 10.00" },
      { jam: "5", waktu: "10.00 - 10.40" },
      { jam: "6", waktu: "10.40 - 11.20" },
      { jam: "", waktu: "11.20 - 11.50", activity: "Istirahat 2 / Sholat Dzuhur Berjamaah" },
      { jam: "7", waktu: "11.50 - 12.25" },
      { jam: "8", waktu: "12.25 - 13.00" },
    ]
  },
  {
    day: "KAMIS",
    rows: [
      { jam: "0", waktu: "06.30 - 07.00", activity: "Apel Pagi / Pembacaan Isitighotsah" },
      { jam: "1", waktu: "07.00 - 07.40" },
      { jam: "2", waktu: "07.40 - 08.20" },
      { jam: "3", waktu: "08.20 - 09.00" },
      { jam: "", waktu: "09.00 - 09.20", activity: "Istirahat ke-1" },
      { jam: "4", waktu: "09.20 - 10.00" },
      { jam: "5", waktu: "10.00 - 10.40" },
      { jam: "6", waktu: "10.40 - 11.20" },
      { jam: "", waktu: "11.20 - 11.50", activity: "Istirahat 2 / Sholat Dzuhur Berjamaah" },
      { jam: "7", waktu: "11.50 - 12.25" },
      { jam: "8", waktu: "12.25 - 13.00" },
    ]
  },
  {
    day: "JUM'AT",
    rows: [
      { jam: "0", waktu: "06.30 - 07.00", activity: "Apel Pagi / Pembacaan Surat Yasin" },
      { jam: "1", waktu: "07.00 - 07.40" },
      { jam: "2", waktu: "07.40 - 08.20" },
      { jam: "3", waktu: "08.20 - 09.00" },
      { jam: "", waktu: "09.00 - 09.20", activity: "Istirahat" },
      { jam: "4", waktu: "09.20 - 10.00" },
      { jam: "5", waktu: "10.00 - 10.40" },
    ]
  },
  {
    day: "SABTU",
    rows: [
      { jam: "0", waktu: "06.30 - 07.00", activity: "Apel Pagi / Pembacaan Asma'ul Husna dan Juz 'Amma" },
      { jam: "1", waktu: "07.00 - 07.40", activity: "Sabtu Sehat Jiwa Raga" },
      { jam: "2", waktu: "07.40 - 08.20" },
      { jam: "3", waktu: "08.20 - 09.00" },
      { jam: "", waktu: "09.00 - 09.20", activity: "Istirahat" },
      { jam: "4", waktu: "09.20 - 10.00" },
      { jam: "5", waktu: "10.00 - 10.40" },
      { jam: "6", waktu: "10.40 - 11.20" },
      { jam: "", waktu: "11.20 - 12.00", activity: "Sholat Dhuhur Berjamaah" },
      { jam: "", waktu: "", activity: "Kegiatan Pengembangan Diri (Ekstra Kurikuler)" },
    ]
  }
];

export const DEFAULT_SCHEDULE_MAP: Record<string, string> = {
  "JUM'AT-1-IX A": "BAJA-SB",
  "JUM'AT-1-IX B": "BIG-RN",
  "JUM'AT-1-IX C": "PJOK-MH",
  "JUM'AT-1-VII A": "MAT-EM",
  "JUM'AT-1-VII B": "IPS-MU",
  "JUM'AT-1-VII C": "BIG-AH",
  "JUM'AT-1-VIII A": "IPS-BR",
  "JUM'AT-1-VIII B": "PKN-EH",
  "JUM'AT-1-VIII C": "IPA-MY",
  "JUM'AT-2-IX A": "BAJA-SB",
  "JUM'AT-2-IX B": "BIG-RN",
  "JUM'AT-2-IX C": "PJOK-MH",
  "JUM'AT-2-VII A": "MAT-EM",
  "JUM'AT-2-VII B": "IPS-MU",
  "JUM'AT-2-VII C": "BIG-AH",
  "JUM'AT-2-VIII A": "IPS-BR",
  "JUM'AT-2-VIII B": "PKN-EH",
  "JUM'AT-2-VIII C": "IPA-MY",
  "JUM'AT-3-IX A": "BIN-SH",
  "JUM'AT-3-IX B": "PAI-RH",
  "JUM'AT-3-IX C": "PJOK-MH",
  "JUM'AT-3-VII A": "BAJA-SB",
  "JUM'AT-3-VII B": "BIN-FW",
  "JUM'AT-3-VII C": "BK-OD",
  "JUM'AT-3-VIII A": "MAT-EM",
  "JUM'AT-3-VIII B": "PKN-EH",
  "JUM'AT-3-VIII C": "BK-MW",
  "JUM'AT-4-IX A": "BIN-SH",
  "JUM'AT-4-IX B": "PAI-RH",
  "JUM'AT-4-IX C": "IPS-MU",
  "JUM'AT-4-VII A": "BAJA-SB",
  "JUM'AT-4-VII B": "BIN-FW",
  "JUM'AT-4-VII C": "IPA-MY",
  "JUM'AT-4-VIII A": "MAT-EM",
  "JUM'AT-4-VIII B": "BIG-RN",
  "JUM'AT-4-VIII C": "MAT-PU",
  "JUM'AT-5-IX A": "BIN-SH",
  "JUM'AT-5-IX B": "PAI-RH",
  "JUM'AT-5-IX C": "IPS-MU",
  "JUM'AT-5-VII A": "BK-OD",
  "JUM'AT-5-VII B": "BIN-FW",
  "JUM'AT-5-VII C": "IPA-MY",
  "JUM'AT-5-VIII A": "MAT-EM",
  "JUM'AT-5-VIII B": "BIG-RN",
  "JUM'AT-5-VIII C": "MAT-PU",
  "KAMIS-1-IX A": "PJOK-MH",
  "KAMIS-1-IX B": "MAT-PU",
  "KAMIS-1-IX C": "BIG-RN",
  "KAMIS-1-VII A": "BIN-FW",
  "KAMIS-1-VII B": "BK-OD",
  "KAMIS-1-VII C": "MAT-EM",
  "KAMIS-1-VIII A": "IPA-MY",
  "KAMIS-1-VIII B": "IPS-BR",
  "KAMIS-1-VIII C": "PAI-RH",
  "KAMIS-2-IX A": "PJOK-MH",
  "KAMIS-2-IX B": "MAT-PU",
  "KAMIS-2-IX C": "BIG-RN",
  "KAMIS-2-VII A": "BIN-FW",
  "KAMIS-2-VII B": "BIG-AH",
  "KAMIS-2-VII C": "MAT-EM",
  "KAMIS-2-VIII A": "IPA-MY",
  "KAMIS-2-VIII B": "IPS-BR",
  "KAMIS-2-VIII C": "PAI-RH",
  "KAMIS-3-IX A": "PJOK-MH",
  "KAMIS-3-IX B": "BIG-RN",
  "KAMIS-3-IX C": "IPA-RB",
  "KAMIS-3-VII A": "BIN-FW",
  "KAMIS-3-VII B": "BIG-AH",
  "KAMIS-3-VII C": "MAT-EM",
  "KAMIS-3-VIII A": "PKN-EH",
  "KAMIS-3-VIII B": "MAT-PU",
  "KAMIS-3-VIII C": "PAI-RH",
  "KAMIS-4-IX A": "PAI-RH",
  "KAMIS-4-IX B": "BIG-RN",
  "KAMIS-4-IX C": "IPA-RB",
  "KAMIS-4-VII A": "MAT-EM",
  "KAMIS-4-VII B": "BIN-FW",
  "KAMIS-4-VII C": "IPS-MU",
  "KAMIS-4-VIII A": "PKN-EH",
  "KAMIS-4-VIII B": "MAT-PU",
  "KAMIS-4-VIII C": "PJOK-MH",
  "KAMIS-5-IX A": "PAI-RH",
  "KAMIS-5-IX B": "IPA-RB",
  "KAMIS-5-IX C": "SENI-FA",
  "KAMIS-5-VII A": "MAT-EM",
  "KAMIS-5-VII B": "BIN-FW",
  "KAMIS-5-VII C": "IPS-MU",
  "KAMIS-5-VIII A": "PKN-EH",
  "KAMIS-5-VIII B": "MAT-PU",
  "KAMIS-5-VIII C": "PJOK-MH",
  "KAMIS-6-IX A": "PAI-RH",
  "KAMIS-6-IX B": "IPA-RB",
  "KAMIS-6-IX C": "SENI-FA",
  "KAMIS-6-VII A": "MAT-EM",
  "KAMIS-6-VII B": "BIN-FW",
  "KAMIS-6-VII C": "PKN-EH",
  "KAMIS-6-VIII A": "BK-MW",
  "KAMIS-6-VIII B": "IPA-MY",
  "KAMIS-6-VIII C": "PJOK-MH",
  "KAMIS-7-IX A": "IPA-RB",
  "KAMIS-7-IX B": "BIN-SH",
  "KAMIS-7-IX C": "MAT-PU",
  "KAMIS-7-VII A": "BIG-AH",
  "KAMIS-7-VII B": "MAT-EM",
  "KAMIS-7-VII C": "PKN-EH",
  "KAMIS-7-VIII A": "SENI-FA",
  "KAMIS-7-VIII B": "IPA-MY",
  "KAMIS-7-VIII C": "IPS-BR",
  "KAMIS-8-IX A": "IPA-RB",
  "KAMIS-8-IX B": "BIN-SH",
  "KAMIS-8-IX C": "MAT-PU",
  "KAMIS-8-VII A": "BIG-AH",
  "KAMIS-8-VII B": "MAT-EM",
  "KAMIS-8-VII C": "PKN-EH",
  "KAMIS-8-VIII A": "SENI-FA",
  "KAMIS-8-VIII B": "IPA-MY",
  "KAMIS-8-VIII C": "IPS-BR",
  "RABU-1-IX A": "MAT-PU",
  "RABU-1-IX B": "PKN-EH",
  "RABU-1-IX C": "IPA-RB",
  "RABU-1-VII A": "BIN-FW",
  "RABU-1-VII B": "INF-FA",
  "RABU-1-VII C": "PJOK-MH",
  "RABU-1-VIII A": "PAI-RH",
  "RABU-1-VIII B": "INF-MY",
  "RABU-1-VIII C": "BIN-SH",
  "RABU-2-IX A": "MAT-PU",
  "RABU-2-IX B": "PKN-EH",
  "RABU-2-IX C": "IPA-RB",
  "RABU-2-VII A": "BIN-FW",
  "RABU-2-VII B": "INF-FA",
  "RABU-2-VII C": "PJOK-MH",
  "RABU-2-VIII A": "PAI-RH",
  "RABU-2-VIII B": "INF-MY",
  "RABU-2-VIII C": "BIN-SH",
  "RABU-3-IX A": "MAT-PU",
  "RABU-3-IX B": "PKN-EH",
  "RABU-3-IX C": "IPA-RB",
  "RABU-3-VII A": "BIN-FW",
  "RABU-3-VII B": "INF-FA",
  "RABU-3-VII C": "PJOK-MH",
  "RABU-3-VIII A": "PAI-RH",
  "RABU-3-VIII B": "INF-MY",
  "RABU-3-VIII C": "BIN-SH",
  "RABU-4-IX A": "IPS-MU",
  "RABU-4-IX B": "INF-AH",
  "RABU-4-IX C": "MAT-PU",
  "RABU-4-VII A": "IPA-RB",
  "RABU-4-VII B": "PKN-EH",
  "RABU-4-VII C": "BIN-FW",
  "RABU-4-VIII A": "PJOK-MH",
  "RABU-4-VIII B": "SENI-FA",
  "RABU-4-VIII C": "BIG-RN",
  "RABU-5-IX A": "IPS-MU",
  "RABU-5-IX B": "INF-AH",
  "RABU-5-IX C": "MAT-PU",
  "RABU-5-VII A": "IPA-RB",
  "RABU-5-VII B": "PKN-EH",
  "RABU-5-VII C": "BIN-FW",
  "RABU-5-VIII A": "PJOK-MH",
  "RABU-5-VIII B": "SENI-FA",
  "RABU-5-VIII C": "BIG-RN",
  "RABU-6-IX A": "BIN-SH",
  "RABU-6-IX B": "INF-AH",
  "RABU-6-IX C": "MAT-PU",
  "RABU-6-VII A": "IPA-RB",
  "RABU-6-VII B": "PKN-EH",
  "RABU-6-VII C": "BIN-FW",
  "RABU-6-VIII A": "PJOK-MH",
  "RABU-6-VIII B": "PAI-RH",
  "RABU-6-VIII C": "IPA-MY",
  "RABU-7-IX A": "BIN-SH",
  "RABU-7-IX B": "IPS-MU",
  "RABU-7-IX C": "BIG-RN",
  "RABU-7-VII A": "BIG-AH",
  "RABU-7-VII B": "IPA-RB",
  "RABU-7-VII C": "SENI-FA",
  "RABU-7-VIII A": "IPS-BR",
  "RABU-7-VIII B": "PAI-RH",
  "RABU-7-VIII C": "IPA-MY",
  "RABU-8-IX A": "BIN-SH",
  "RABU-8-IX B": "IPS-MU",
  "RABU-8-IX C": "BIG-RN",
  "RABU-8-VII A": "BIG-AH",
  "RABU-8-VII B": "IPA-RB",
  "RABU-8-VII C": "SENI-FA",
  "RABU-8-VIII A": "IPS-BR",
  "RABU-8-VIII B": "PAI-RH",
  "RABU-8-VIII C": "IPA-MY",
  "SABTU-2-IX A": "MAT-PU",
  "SABTU-2-IX B": "IPA-RB",
  "SABTU-2-IX C": "IPS-MU",
  "SABTU-2-VII A": "PKN-EH",
  "SABTU-2-VII B": "BIG-AH",
  "SABTU-2-VII C": "BAJA-SB",
  "SABTU-2-VIII A": "MAT-EM",
  "SABTU-2-VIII B": "PJOK-MH",
  "SABTU-2-VIII C": "SENI-FA",
  "SABTU-3-IX A": "MAT-PU",
  "SABTU-3-IX B": "IPA-RB",
  "SABTU-3-IX C": "IPS-MU",
  "SABTU-3-VII A": "PKN-EH",
  "SABTU-3-VII B": "BIG-AH",
  "SABTU-3-VII C": "BAJA-SB",
  "SABTU-3-VIII A": "MAT-EM",
  "SABTU-3-VIII B": "PJOK-MH",
  "SABTU-3-VIII C": "SENI-FA",
  "SABTU-4-IX A": "BK-OD",
  "SABTU-4-IX B": "IPA-RB",
  "SABTU-4-IX C": "PAI-RH",
  "SABTU-4-VII A": "PKN-EH",
  "SABTU-4-VII B": "MAT-EM",
  "SABTU-4-VII C": "IPA-MY",
  "SABTU-4-VIII A": "BIN-FW",
  "SABTU-4-VIII B": "PJOK-MH",
  "SABTU-4-VIII C": "BIN-SH",
  "SABTU-5-IX A": "BIG-RN",
  "SABTU-5-IX B": "SENI-FA",
  "SABTU-5-IX C": "PAI-RH",
  "SABTU-5-VII A": "IPS-MU",
  "SABTU-5-VII B": "MAT-EM",
  "SABTU-5-VII C": "IPA-MY",
  "SABTU-5-VIII A": "BIN-FW",
  "SABTU-5-VIII B": "BAJA-SB",
  "SABTU-5-VIII C": "BIN-SH",
  "SABTU-6-IX A": "BIG-RN",
  "SABTU-6-IX B": "SENI-FA",
  "SABTU-6-IX C": "PAI-RH",
  "SABTU-6-VII A": "IPS-MU",
  "SABTU-6-VII B": "MAT-EM",
  "SABTU-6-VII C": "IPA-MY",
  "SABTU-6-VIII A": "BIN-FW",
  "SABTU-6-VIII B": "BAJA-SB",
  "SABTU-6-VIII C": "BIN-SH",
  "SELASA-1-IX A": "PKN-EH",
  "SELASA-1-IX B": "MAT-PU",
  "SELASA-1-IX C": "BIN-SH",
  "SELASA-1-VII A": "PJOK-MH",
  "SELASA-1-VII B": "PAI-RH",
  "SELASA-1-VII C": "INF-FA",
  "SELASA-1-VIII A": "BIN-FW",
  "SELASA-1-VIII B": "BIG-RN",
  "SELASA-1-VIII C": "BAJA-SB",
  "SELASA-2-IX A": "PKN-EH",
  "SELASA-2-IX B": "MAT-PU",
  "SELASA-2-IX C": "BIN-SH",
  "SELASA-2-VII A": "PJOK-MH",
  "SELASA-2-VII B": "PAI-RH",
  "SELASA-2-VII C": "INF-FA",
  "SELASA-2-VIII A": "BIN-FW",
  "SELASA-2-VIII B": "BIG-RN",
  "SELASA-2-VIII C": "BAJA-SB",
  "SELASA-3-IX A": "PKN-EH",
  "SELASA-3-IX B": "MAT-PU",
  "SELASA-3-IX C": "BIN-SH",
  "SELASA-3-VII A": "PJOK-MH",
  "SELASA-3-VII B": "PAI-RH",
  "SELASA-3-VII C": "INF-FA",
  "SELASA-3-VIII A": "BIN-FW",
  "SELASA-3-VIII B": "BK-MW",
  "SELASA-3-VIII C": "INF-EM",
  "SELASA-4-IX A": "IPA-RB",
  "SELASA-4-IX B": "BK-OD",
  "SELASA-4-IX C": "BAJA-SB",
  "SELASA-4-VII A": "INF-FA",
  "SELASA-4-VII B": "PJOK-MH",
  "SELASA-4-VII C": "IPS-MU",
  "SELASA-4-VIII A": "IPA-MY",
  "SELASA-4-VIII B": "BIN-FW",
  "SELASA-4-VIII C": "INF-EM",
  "SELASA-5-IX A": "IPA-RB",
  "SELASA-5-IX B": "BIN-SH",
  "SELASA-5-IX C": "BAJA-SB",
  "SELASA-5-VII A": "INF-FA",
  "SELASA-5-VII B": "PJOK-MH",
  "SELASA-5-VII C": "IPS-MU",
  "SELASA-5-VIII A": "IPA-MY",
  "SELASA-5-VIII B": "BIN-FW",
  "SELASA-5-VIII C": "INF-EM",
  "SELASA-6-IX A": "IPA-RB",
  "SELASA-6-IX B": "BIN-SH",
  "SELASA-6-IX C": "INF-AH",
  "SELASA-6-VII A": "INF-FA",
  "SELASA-6-VII B": "PJOK-MH",
  "SELASA-6-VII C": "PAI-RH",
  "SELASA-6-VIII A": "IPA-MY",
  "SELASA-6-VIII B": "BIN-FW",
  "SELASA-6-VIII C": "PKN-EH",
  "SELASA-7-IX A": "IPS-MU",
  "SELASA-7-IX B": "BAJA-SB",
  "SELASA-7-IX C": "INF-AH",
  "SELASA-7-VII A": "IPA-RB",
  "SELASA-7-VII B": "SENI-FA",
  "SELASA-7-VII C": "PAI-RH",
  "SELASA-7-VIII A": "BIG-RN",
  "SELASA-7-VIII B": "IPS-BR",
  "SELASA-7-VIII C": "PKN-EH",
  "SELASA-8-IX A": "IPS-MU",
  "SELASA-8-IX B": "BAJA-SB",
  "SELASA-8-IX C": "INF-AH",
  "SELASA-8-VII A": "IPA-RB",
  "SELASA-8-VII B": "SENI-FA",
  "SELASA-8-VII C": "PAI-RH",
  "SELASA-8-VIII A": "BIG-RN",
  "SELASA-8-VIII B": "IPS-BR",
  "SELASA-8-VIII C": "PKN-EH",
  "SENIN-2-IX A": "INF-EM",
  "SENIN-2-IX B": "IPS-MU",
  "SENIN-2-IX C": "BIN-SH",
  "SENIN-2-VII A": "SENI-FA",
  "SENIN-2-VII B": "IPA-RB",
  "SENIN-2-VII C": "BIN-FW",
  "SENIN-2-VIII A": "BIG-RN",
  "SENIN-2-VIII B": "IPA-MY",
  "SENIN-2-VIII C": "IPS-BR",
  "SENIN-3-IX A": "INF-EM",
  "SENIN-3-IX B": "IPS-MU",
  "SENIN-3-IX C": "BIN-SH",
  "SENIN-3-VII A": "SENI-FA",
  "SENIN-3-VII B": "IPA-RB",
  "SENIN-3-VII C": "BIN-FW",
  "SENIN-3-VIII A": "BIG-RN",
  "SENIN-3-VIII B": "IPA-MY",
  "SENIN-3-VIII C": "IPS-BR",
  "SENIN-4-IX A": "INF-EM",
  "SENIN-4-IX B": "PJOK-MH",
  "SENIN-4-IX C": "BIN-SH",
  "SENIN-4-VII A": "PAI-RH",
  "SENIN-4-VII B": "IPA-RB",
  "SENIN-4-VII C": "BIN-FW",
  "SENIN-4-VIII A": "BAJA-SB",
  "SENIN-4-VIII B": "MAT-PU",
  "SENIN-4-VIII C": "BIG-RN",
  "SENIN-5-IX A": "SENI-FA",
  "SENIN-5-IX B": "PJOK-MH",
  "SENIN-5-IX C": "BK-OD",
  "SENIN-5-VII A": "PAI-RH",
  "SENIN-5-VII B": "IPS-MU",
  "SENIN-5-VII C": "BIG-AH",
  "SENIN-5-VIII A": "BAJA-SB",
  "SENIN-5-VIII B": "MAT-PU",
  "SENIN-5-VIII C": "BIG-RN",
  "SENIN-6-IX A": "SENI-FA",
  "SENIN-6-IX B": "PJOK-MH",
  "SENIN-6-IX C": "PKN-EH",
  "SENIN-6-VII A": "PAI-RH",
  "SENIN-6-VII B": "IPS-MU",
  "SENIN-6-VII C": "BIG-AH",
  "SENIN-6-VIII A": "INF-MY",
  "SENIN-6-VIII B": "BIN-FW",
  "SENIN-6-VIII C": "MAT-PU",
  "SENIN-7-IX A": "BIG-RN",
  "SENIN-7-IX B": "BIN-SH",
  "SENIN-7-IX C": "PKN-EH",
  "SENIN-7-VII A": "IPS-MU",
  "SENIN-7-VII B": "BAJA-SB",
  "SENIN-7-VII C": "MAT-EM",
  "SENIN-7-VIII A": "INF-MY",
  "SENIN-7-VIII B": "BIN-FW",
  "SENIN-7-VIII C": "MAT-PU",
  "SENIN-8-IX A": "BIG-RN",
  "SENIN-8-IX B": "BIN-SH",
  "SENIN-8-IX C": "PKN-EH",
  "SENIN-8-VII A": "IPS-MU",
  "SENIN-8-VII B": "BAJA-SB",
  "SENIN-8-VII C": "MAT-EM",
  "SENIN-8-VIII A": "INF-MY",
  "SENIN-8-VIII B": "BIN-FW",
  "SENIN-8-VIII C": "MAT-PU"
};

export const INITIAL_LEAVES: TeacherLeave[] = [
  {
    "date": "2026-01-07",
    "description": "Izin menjenguk nenek di surabaya",
    "id": "1767756783489",
    "teacherId": 14,
    "teacherName": "Fakhita Madury, S.Sn",
    "type": "SAKIT"
  },
  {
    "date": "2026-01-07",
    "description": "Izin ada kegiatan dinas luar",
    "id": "1767756808520",
    "teacherId": 11,
    "teacherName": "Rebby Dwi Prataopu, S.Si",
    "type": "SAKIT"
  },
  {
    "date": "2025-12-24",
    "description": "Demam",
    "id": "1766565942056",
    "teacherId": 2,
    "teacherName": "Bakhtiar Rifai, SE",
    "type": "SAKIT"
  }
];

export const INITIAL_AGENDAS: TeacherAgenda[] = [
  {
    "activity": "Rapat pembagian tugas mengaajar di Lab IPA",
    "date": "2026-01-07",
    "id": "1767749629708",
    "remarks": "Selesai",
    "teacherName": "Rudi Hermawan, S.Pd.I",
    "timeEnd": "09:00",
    "timeStart": "07:00"
  },
  {
    "activity": "Melaksanakan PKKS tahun 2025 di Lab IPA dengan penilai Abah Sunartono dan Bu Rodhiyah",
    "date": "2026-01-05",
    "id": "1767749663015",
    "remarks": "Terlaksana",
    "teacherName": "Rudi Hermawan, S.Pd.I",
    "timeEnd": "08:00",
    "timeStart": "07:00"
  },
  {
    "activity": "Penyusunan dan Revisi Program Semester Genap Kelas 7 dan 9",
    "date": "2026-01-02",
    "id": "1767753393144",
    "remarks": "Terlaksana",
    "teacherName": "Okha Devi Anggraini, S.Pd.",
    "timeEnd": "11:00",
    "timeStart": "07:00"
  },
  {
    "activity": "Penyusunan RPL/Modul Layanan Kelas 7 dan 9",
    "date": "2026-01-03",
    "id": "1767753644486",
    "remarks": "Terlaksana",
    "teacherName": "Okha Devi Anggraini, S.Pd.",
    "timeEnd": "12:30",
    "timeStart": "07:00"
  },
  {
    "activity": "Melaksanakan kegiatan PKKS Tahun 2025",
    "date": "2026-01-05",
    "id": "1767753732959",
    "remarks": "Terlaksana",
    "teacherName": "Okha Devi Anggraini, S.Pd.",
    "timeEnd": "14:00",
    "timeStart": "07:00"
  },
  {
    "activity": "Rapat Pembagian Jam dan Tugas Mengajar Semester Genap TP 2025-2026",
    "date": "2026-01-06",
    "id": "1767753790353",
    "remarks": "Selesai",
    "teacherName": "Okha Devi Anggraini, S.Pd.",
    "timeEnd": "14:00",
    "timeStart": "07:00"
  },
  {
    "activity": "Penyusunan Materi, Media dan LKPD Layanan Kelas 7 dan 9",
    "date": "2026-01-07",
    "id": "1767753869583",
    "remarks": "Terlaksana",
    "teacherName": "Okha Devi Anggraini, S.Pd.",
    "timeEnd": "14:00",
    "timeStart": "07:00"
  },
  {
    "activity": "mengajar kelas 9a",
    "date": "2026-01-07",
    "id": "1767757960510",
    "remarks": "Terlaksana",
    "teacherName": "Purnadi, S. Pd.",
    "timeEnd": "08:56",
    "timeStart": "07:00"
  },
  {
    "activity": "mengajar kelas 9c",
    "date": "2026-01-07",
    "id": "1767758047992",
    "remarks": "Terlaksana",
    "teacherName": "Purnadi, S. Pd.",
    "timeEnd": "11:15",
    "timeStart": "09:00"
  },
  {
    "activity": "Mengajar di kelas IX A ",
    "date": "2026-01-07",
    "id": "1767760529651",
    "remarks": "Terlaksana",
    "teacherName": "Israfin Maria Ulfa, S.Pd",
    "timeEnd": "10:40",
    "timeStart": "09:20"
  },
  {
    "activity": "Mengajar di kelas IX B",
    "date": "2026-01-07",
    "id": "1767762539486",
    "remarks": "Terlaksana",
    "teacherName": "Israfin Maria Ulfa, S.Pd",
    "timeEnd": "13:00",
    "timeStart": "11:50"
  },
  {
    "activity": "Rapat Koordinasi dengan kepala sekolah",
    "date": "2026-01-08",
    "id": "1767833379317",
    "remarks": "Selesai",
    "teacherName": "Rudi Hermawan, S.Pd.I",
    "timeEnd": "09:00",
    "timeStart": "07:00"
  },
  {
    "activity": "Menyusun jadwal pelajaran, jadwal supervisi",
    "date": "2026-01-08",
    "id": "1767833584163",
    "remarks": "proses",
    "teacherName": "Rudi Hermawan, S.Pd.I",
    "timeEnd": "12:00",
    "timeStart": "09:00"
  },
  {
    "activity": "Rapat koordinasi bersama Kepala Sekolah dan seluruh guru",
    "date": "2026-01-08",
    "id": "1767856178735",
    "remarks": "Selesai",
    "teacherName": "Israfin Maria Ulfa, S.Pd",
    "timeEnd": "08:30",
    "timeStart": "07:30"
  },
  {
    "activity": "Mengajar di kelas VII C",
    "date": "2026-01-08",
    "id": "1767856223525",
    "remarks": "Terlaksana",
    "teacherName": "Israfin Maria Ulfa, S.Pd",
    "timeEnd": "10:40",
    "timeStart": "09:20"
  },
  {
    "activity": "Mengajar di kelas VII A",
    "date": "2026-01-08",
    "id": "1767856283433",
    "remarks": "Terlaksana",
    "teacherName": "Israfin Maria Ulfa, S.Pd",
    "timeEnd": "13:00",
    "timeStart": "12:10"
  },
  {
    "activity": "Mendampingi siswa melaksanakan sholat Dhuhur di mushola",
    "date": "2026-01-08",
    "id": "1767856390243",
    "remarks": "Terlaksana",
    "teacherName": "Israfin Maria Ulfa, S.Pd",
    "timeEnd": "12:10",
    "timeStart": "11:30"
  },
  {
    "activity": "Rapat Koordinasi Aplikasi Jurnal Mengajar ",
    "date": "2026-01-08",
    "id": "1767859169409",
    "remarks": "Selesai",
    "teacherName": "Okha Devi Anggraini, S.Pd.",
    "timeEnd": "08:00",
    "timeStart": "07:00"
  },
  {
    "activity": "Sertijab Wali Kelas 7C ke Bu Fakhita Madury, S.Sn bersama siswa kelas 7C",
    "date": "2026-01-08",
    "id": "1767859263148",
    "remarks": "Terlaksana",
    "teacherName": "Okha Devi Anggraini, S.Pd.",
    "timeEnd": "13:00",
    "timeStart": "12:00"
  },
  {
    "activity": "Mengajar di kelas VII B",
    "date": "2026-01-09",
    "id": "1767931592869",
    "remarks": "Terlaksana",
    "teacherName": "Israfin Maria Ulfa, S.Pd",
    "timeEnd": "08:20",
    "timeStart": "07:00"
  },
  {
    "activity": "Mengajar di kelas IX C",
    "date": "2026-01-09",
    "id": "1767931632947",
    "remarks": "Terlaksana",
    "teacherName": "Israfin Maria Ulfa, S.Pd",
    "timeEnd": "11:40",
    "timeStart": "09:20"
  },
  {
    "activity": "Mengajar di kelas IX C",
    "date": "2026-01-10",
    "id": "1768190229538",
    "remarks": "Terlaksana",
    "teacherName": "Israfin Maria Ulfa, S.Pd",
    "timeEnd": "09:00",
    "timeStart": "07:40"
  },
  {
    "activity": "Mendampingi siswa kelas IX dalam pelaksanaan Try Out TKA",
    "date": "2026-01-12",
    "id": "1768190572106",
    "remarks": "Terlaksana",
    "teacherName": "Israfin Maria Ulfa, S.Pd",
    "timeEnd": "10:00",
    "timeStart": "08:00"
  },
  {
    "activity": "Musyawarah dengan kelas 7A untuk persiapan kegiatan PHBI Isro' Mi'roj",
    "date": "2026-01-15",
    "id": "1768575550369",
    "remarks": "Terlaksana",
    "teacherName": "Israfin Maria Ulfa, S.Pd",
    "timeEnd": "13:00",
    "timeStart": "12:05"
  },
  {
    "activity": "Mengikuti kegiatan Peringatan Isra' Mi'raj",
    "date": "2026-01-17",
    "id": "1768796006747",
    "remarks": "Terlaksana",
    "teacherName": "Okha Devi Anggraini, S.Pd.",
    "timeEnd": "11:00",
    "timeStart": "07:00"
  },
  {
    "activity": "mengajar di kelas 9-B jam ke 4,5",
    "date": "2026-01-20",
    "id": "1768879956865",
    "remarks": "Terlaksana",
    "teacherName": "Dra. Sri Hayati",
    "timeEnd": "11:40",
    "timeStart": "10:30"
  },
  {
    "activity": "mengajar di kelas 9-C jam ke 1,2,3",
    "date": "2026-01-20",
    "id": "1768880079676",
    "remarks": "Terlaksana",
    "teacherName": "Dra. Sri Hayati",
    "timeEnd": "09:00",
    "timeStart": "07:00"
  },
  {
    "activity": "Mengikuti kegiatan MGMP Kabupaten di SMPN 1 Puri",
    "date": "2026-01-20",
    "id": "1768910790580",
    "remarks": "Terlaksana",
    "teacherName": "Israfin Maria Ulfa, S.Pd",
    "timeEnd": "12:00",
    "timeStart": "08:00"
  },
  {
    "activity": "Melakukan transaksi non tunai Honor GTT dan Upah PPPK PW (tugas Bendahara BOSP)",
    "date": "2026-01-20",
    "id": "1768974288081",
    "remarks": "Terlaksana",
    "teacherName": "Okha Devi Anggraini, S.Pd.",
    "timeEnd": "14:00",
    "timeStart": "12:00"
  },
  {
    "activity": "Melakukan pembayaran pajak dan konfirmasi penyaluran dana BOSP di website BOS Salur Kemendikdasmen",
    "date": "2026-01-21",
    "id": "1768974351360",
    "remarks": "Terlaksana",
    "teacherName": "Okha Devi Anggraini, S.Pd.",
    "timeEnd": "14:00",
    "timeStart": "07:00"
  },
  {
    "activity": "Mengajar di kelas IX A",
    "date": "2026-01-21",
    "id": "1768979553211",
    "remarks": "Terlaksana",
    "teacherName": "Israfin Maria Ulfa, S.Pd",
    "timeEnd": "10:40",
    "timeStart": "09:20"
  },
  {
    "activity": "Mengajar di kelas IX B",
    "date": "2026-01-21",
    "id": "1768979583660",
    "remarks": "Terlaksana",
    "teacherName": "Israfin Maria Ulfa, S.Pd",
    "timeEnd": "13:00",
    "timeStart": "12:10"
  },
  {
    "activity": "Mengajar di kelas VII C",
    "date": "2026-01-22",
    "id": "1769064668102",
    "remarks": "Terlaksana",
    "teacherName": "Israfin Maria Ulfa, S.Pd",
    "timeEnd": "10:40",
    "timeStart": "09:20"
  },
  {
    "activity": "membawa",
    "date": "2025-12-24",
    "id": "1766566543261",
    "remarks": "",
    "teacherName": "Purnadi, S. Pd.",
    "timeEnd": "08:00",
    "timeStart": "07:00"
  },
  {
    "activity": "mengajar di kelas",
    "date": "2025-12-24",
    "id": "1766571201192",
    "remarks": "",
    "teacherName": "Rudi Hermawan, S.Pd.I",
    "timeEnd": "08:00",
    "timeStart": "07:00"
  }
];

export const INITIAL_ATTITUDE: AttitudeRecord[] = [
  {
    "actionTaken": "Bimbingan individu",
    "behavior": "Terlambat masuk kelas",
    "className": "IX C",
    "date": "2025-12-24",
    "id": "1766591457237mhn",
    "notes": "Perlu pantauan berkelanjutan",
    "studentId": "242",
    "teacherName": "Purnadi, S. Pd."
  },
  {
    "actionTaken": "Teguran lisan",
    "behavior": "Tidak mengerjakan tugas",
    "className": "IX C",
    "date": "2025-12-27",
    "id": "1766717442987su5",
    "notes": "Perlu pantauan berkelanjutan",
    "studentId": "243",
    "teacherName": "Purnadi, S. Pd."
  },
  {
    "actionTaken": "Teguran & pembinaan disiplin",
    "behavior": "Terlambat masuk kelas",
    "className": "VII A",
    "date": "2025-12-31",
    "id": "1767150288908e26",
    "notes": "Siswa diingatkan pentingnya waktu",
    "studentId": "2",
    "teacherName": "Fakhita Madury, S.Sn"
  },
  {
    "actionTaken": "Teguran & pembinaan disiplin",
    "behavior": "Terlambat masuk kelas",
    "className": "VII A",
    "date": "2025-12-31",
    "id": "1767150301853dyf",
    "notes": "Siswa diingatkan pentingnya waktu",
    "studentId": "3",
    "teacherName": "Fakhita Madury, S.Sn"
  },
  {
    "actionTaken": "Teguran lisan, minta izin masuk ke kesiswaan",
    "behavior": "tidak mengikuti pelajaran karena datang terlambat",
    "className": "VIII A",
    "date": "2026-01-07",
    "id": "17677482064364rd",
    "notes": "pembinaan",
    "studentId": "105",
    "teacherName": "Rudi Hermawan, S.Pd.I"
  },
  {
    "actionTaken": "Teguran & pembinaan disiplin",
    "behavior": "Terlambat masuk kelas",
    "className": "VIII A",
    "date": "2026-01-07",
    "id": "1767748297048g0h",
    "notes": "Siswa diingatkan pentingnya waktu",
    "studentId": "111",
    "teacherName": "Rudi Hermawan, S.Pd.I"
  },
  {
    "actionTaken": "Teguran & pembinaan disiplin",
    "behavior": "Terlambat masuk kelas",
    "className": "VIII A",
    "date": "2026-01-07",
    "id": "1767748318882m82",
    "notes": "Siswa diingatkan pentingnya waktu",
    "studentId": "95",
    "teacherName": "Rudi Hermawan, S.Pd.I"
  },
  {
    "actionTaken": "Teguran & pembinaan disiplin",
    "behavior": "Terlambat masuk kelas",
    "className": "VIII A",
    "date": "2026-01-07",
    "id": "17677483420222k1",
    "notes": "Siswa diingatkan pentingnya waktu",
    "studentId": "94",
    "teacherName": "Rudi Hermawan, S.Pd.I"
  },
  {
    "actionTaken": "Pembinaan karakter",
    "behavior": "Berkata kurang sopan",
    "className": "IX C",
    "date": "2026-01-07",
    "id": "17677495840537qp",
    "notes": "Edukasi tentang etika berbicara",
    "studentId": "252",
    "teacherName": "Rudi Hermawan, S.Pd.I"
  },
  {
    "actionTaken": "menulis istighfar 50 kali",
    "behavior": "Berkata kurang sopan",
    "className": "VIII A",
    "date": "2026-01-07",
    "id": "1767749806545r1o",
    "notes": "Edukasi tentang etika berbicara",
    "studentId": "83",
    "teacherName": "Rudi Hermawan, S.Pd.I"
  },
  {
    "actionTaken": "Teguran & pembinaan disiplin",
    "behavior": "Terlambat masuk kelas",
    "className": "VIII A",
    "date": "2026-01-07",
    "id": "1767749949906y8r",
    "notes": "Siswa diingatkan pentingnya waktu",
    "studentId": "88",
    "teacherName": "Rudi Hermawan, S.Pd.I"
  },
  {
    "actionTaken": "Teguran lisan",
    "behavior": "Tidak membawa buku Bahasa Indonesia ",
    "className": "VII A",
    "date": "2026-01-07",
    "id": "1767757726901yd2",
    "notes": "Sudah ada perubahan perilaku",
    "studentId": "16",
    "teacherName": "Fahmi Wahyuni, S.Pd"
  },
  {
    "actionTaken": "Teguran lisan",
    "behavior": "Terlambat masuk kelas",
    "className": "VII C",
    "date": "2026-01-07",
    "id": "1767757772074j53",
    "notes": "Siswa diingatkan pentingnya waktu",
    "studentId": "73",
    "teacherName": "Fahmi Wahyuni, S.Pd"
  },
  {
    "actionTaken": "Teguran lisan",
    "behavior": "Jujur mengakui kesalahan setelah melanggar peraturan sekolah",
    "className": "IX A",
    "date": "2026-01-07",
    "id": "1767762683519kgk",
    "notes": "Memiliki niat baik untuk berubah",
    "studentId": "207",
    "teacherName": "Israfin Maria Ulfa, S.Pd"
  },
  {
    "actionTaken": "Teguran lisan",
    "behavior": "Denis pulang tanpa izin, Farhan tidak masuk kelas",
    "className": "VII B",
    "date": "2026-01-08",
    "id": "1767842736213rkr",
    "notes": "Perlu pantauan berkelanjutan",
    "studentId": "40",
    "teacherName": "Fahmi Wahyuni, S.Pd"
  },
  {
    "actionTaken": "Teguran & pembinaan disiplin",
    "behavior": "Terlambat masuk kelas",
    "className": "VII C",
    "date": "2026-01-08",
    "id": "17678567295486cd",
    "notes": "Siswa diingatkan pentingnya waktu",
    "studentId": "64",
    "teacherName": "Israfin Maria Ulfa, S.Pd"
  },
  {
    "actionTaken": "Teguran lisan dan penegasan kewajiban mengikuti kegiatan pembelajaran",
    "behavior": "Tidak mengikuti kegiatan pembelajaran di kelas",
    "className": "VII C",
    "date": "2026-01-08",
    "id": "17678569658539hu",
    "notes": "Siswa kooperatif saat dibina",
    "studentId": "73",
    "teacherName": "Israfin Maria Ulfa, S.Pd"
  },
  {
    "actionTaken": "Teguran lisan dan pembinaan disiplin\n",
    "behavior": "Berada di luar kelas dan tidak mengikuti kegiatan PBM di kelas ",
    "className": "IX C",
    "date": "2026-01-09",
    "id": "1767932014756e4z",
    "notes": "Perlu pantauan berkelanjutan",
    "studentId": "266",
    "teacherName": "Israfin Maria Ulfa, S.Pd"
  },
  {
    "actionTaken": "Teguran & pembinaan disiplin",
    "behavior": "Terlambat masuk kelas",
    "className": "VII C",
    "date": "2026-01-08",
    "id": "1767932098574mc1",
    "notes": "Siswa diingatkan pentingnya waktu",
    "studentId": "65",
    "teacherName": "Israfin Maria Ulfa, S.Pd"
  },
  {
    "actionTaken": "Teguran lisan",
    "behavior": "Tidak masuk kelas ",
    "className": "VIII A",
    "date": "2026-01-10",
    "id": "1768209560628244",
    "notes": "Perlu pantauan berkelanjutan",
    "studentId": "94",
    "teacherName": "Fahmi Wahyuni, S.Pd"
  },
  {
    "actionTaken": "Teguran lisan",
    "behavior": "Tidak masuk kelas",
    "className": "VIII A",
    "date": "2026-01-10",
    "id": "1768209738951iep",
    "notes": "Perlu pantauan berkelanjutan",
    "studentId": "111",
    "teacherName": "Fahmi Wahyuni, S.Pd"
  },
  {
    "actionTaken": "Teguran lisan",
    "behavior": "Pulang tanpa izin",
    "className": "VII B",
    "date": "2026-01-08",
    "id": "1768209821779nt5",
    "notes": "Perlu pantauan berkelanjutan",
    "studentId": "29",
    "teacherName": "Fahmi Wahyuni, S.Pd"
  },
  {
    "actionTaken": "Teguran lisan",
    "behavior": "Tidak masuk kelas ",
    "className": "VIII A",
    "date": "2026-01-10",
    "id": "1768209882151rn2",
    "notes": "Perlu pantauan berkelanjutan",
    "studentId": "78",
    "teacherName": "Fahmi Wahyuni, S.Pd"
  },
  {
    "actionTaken": "Teguran lisan",
    "behavior": "Tidak masuk kelas",
    "className": "VIII A",
    "date": "2026-01-10",
    "id": "1768209920188deq",
    "notes": "Perlu pantauan berkelanjutan",
    "studentId": "88",
    "teacherName": "Fahmi Wahyuni, S.Pd"
  },
  {
    "actionTaken": "Teguran lisan",
    "behavior": "Tidak masuk kelas ",
    "className": "VIII A",
    "date": "2026-01-10",
    "id": "1768209953068v9t",
    "notes": "Perlu pantauan berkelanjutan",
    "studentId": "90",
    "teacherName": "Fahmi Wahyuni, S.Pd"
  },
  {
    "actionTaken": "Teguran lisan",
    "behavior": "Tidak masuk kelas",
    "className": "VIII A",
    "date": "2026-01-10",
    "id": "1768210089478wdy",
    "notes": "Perlu pantauan berkelanjutan",
    "studentId": "91",
    "teacherName": "Fahmi Wahyuni, S.Pd"
  },
  {
    "actionTaken": "Teguran lisan",
    "behavior": "Tidak masuk kelas ",
    "className": "VIII A",
    "date": "2026-01-10",
    "id": "1768210135379yhu",
    "notes": "Perlu pantauan berkelanjutan",
    "studentId": "93",
    "teacherName": "Fahmi Wahyuni, S.Pd"
  },
  {
    "actionTaken": "Teguran lisan",
    "behavior": "Tidak masuk kelas ",
    "className": "VIII A",
    "date": "2026-01-10",
    "id": "176821018280469r",
    "notes": "Perlu pantauan berkelanjutan",
    "studentId": "95",
    "teacherName": "Fahmi Wahyuni, S.Pd"
  },
  {
    "actionTaken": "Teguran lisan",
    "behavior": "Tidak masuk kelas",
    "className": "VIII A",
    "date": "2026-01-10",
    "id": "1768210204448gmm",
    "notes": "Perlu pantauan berkelanjutan",
    "studentId": "103",
    "teacherName": "Fahmi Wahyuni, S.Pd"
  },
  {
    "actionTaken": "Teguran lisan",
    "behavior": "Tidak masuk kelas ",
    "className": "VIII A",
    "date": "2026-01-10",
    "id": "1768210221210c6t",
    "notes": "Perlu pantauan berkelanjutan",
    "studentId": "111",
    "teacherName": "Fahmi Wahyuni, S.Pd"
  },
  {
    "actionTaken": "Pemanggilan orang tua",
    "behavior": "Membawa HP tanpa ijin guru dan bermain HP saat pelajaran",
    "className": "VII A",
    "date": "2026-01-15",
    "id": "1768575687182gku",
    "notes": "Sudah dikomunikasikan ke orang tua",
    "studentId": "24",
    "teacherName": "Israfin Maria Ulfa, S.Pd"
  },
  {
    "actionTaken": "Pemanggilan orang tua",
    "behavior": "Bermain HP saat pelajaran",
    "className": "VII A",
    "date": "2026-01-15",
    "id": "1768575714702702",
    "notes": "Sudah dikomunikasikan ke orang tua",
    "studentId": "13",
    "teacherName": "Israfin Maria Ulfa, S.Pd"
  },
  {
    "actionTaken": "Bimbingan individu",
    "behavior": "Aktif mengerjakan tugas yang diberikan guru. Namun, masih belum mau masuk ke dalam kelas",
    "className": "VII A",
    "date": "2026-01-15",
    "id": "1768575788199m62",
    "notes": "Perlu pantauan berkelanjutan",
    "studentId": "9",
    "teacherName": "Israfin Maria Ulfa, S.Pd"
  },
  {
    "actionTaken": "Pembinaan karakter",
    "behavior": "Berkata kurang sopan",
    "className": "VIII A",
    "date": "2026-01-20",
    "id": "1768998488505h3g",
    "notes": "Edukasi tentang etika berbicara",
    "studentId": "112",
    "teacherName": "Fahmi Wahyuni, S.Pd"
  },
  {
    "actionTaken": "Pembinaan karakter",
    "behavior": "Berkata kurang sopan",
    "className": "VIII A",
    "date": "2026-01-20",
    "id": "1768998519251unx",
    "notes": "Edukasi tentang etika berbicara",
    "studentId": "105",
    "teacherName": "Fahmi Wahyuni, S.Pd"
  },
  {
    "actionTaken": "Penugasan khusus",
    "behavior": "Tidak mengikuti pelajaran IPS selama 4x karena tidak masuk tanpa keterangan (alpa)",
    "className": "VII C",
    "date": "2026-01-22",
    "id": "1769064776007vk4",
    "notes": "Perlu pantauan berkelanjutan",
    "studentId": "69",
    "teacherName": "Israfin Maria Ulfa, S.Pd"
  },
  {
    "actionTaken": "Pemberian sanksi berupa piket ruang kelas dan halaman kelas selama 1 minggu",
    "behavior": "Melempar makanan MBG untuk mainan",
    "className": "VII A",
    "date": "2026-01-22",
    "id": "1769064953043cs6",
    "notes": "Perlu pantauan berkelanjutan",
    "studentId": "11",
    "teacherName": "Israfin Maria Ulfa, S.Pd"
  }
];

export const INITIAL_HOMEROOM: HomeroomRecord[] = [
  {
    "className": "IX C",
    "date": "2025-12-24",
    "id": "17665911914703q4",
    "notes": "",
    "solution": "Bimbingan individu dan nasehat lisan",
    "studentId": "242",
    "teacherName": "Purnadi, S. Pd.",
    "violationType": "Sering datang terlambat ke sekolah"
  },
  {
    "className": "IX C",
    "date": "2025-12-20",
    "id": "17667170563712hu",
    "notes": "",
    "solution": "Bimbingan individu dan nasehat lisan",
    "studentId": "243",
    "teacherName": "Purnadi, S. Pd.",
    "violationType": "Sering datang terlambat ke sekolah"
  },
  {
    "className": "VII A",
    "date": "2026-01-07",
    "id": "1767760975215qab",
    "notes": "",
    "solution": "Dipanggil ke ruang BK dan diberi tugas mandiri oleh guru mapel",
    "studentId": "9",
    "teacherName": "Israfin Maria Ulfa, S.Pd",
    "violationType": "Tidak mau masuk ke dalam kelas untuk mengikuti kegiatan pembelajaran"
  }
];

export const INITIAL_GRADES: GradeRecord[] = [
  {
    "academicYear": "2025/2026",
    "chapters": {
      "1": { "avg": 12.33, "f1": 2, "f2": 2, "f3": 33 },
      "2": { "avg": 3, "f1": 3, "f2": 3, "f5": 3 },
      "3": { "avg": 18, "f1": 33, "f2": 3, "f4": 3, "f5": 33 },
      "4": { "avg": 93, "f1": 3, "f2": 333, "f4": 3, "f5": 33 },
      "5": { "avg": 10.5, "f1": 33, "f2": 3, "f4": 3, "f5": 3 }
    },
    "className": "IX C",
    "finalGrade": 11.12,
    "id": "242_Matematika_Genap",
    "sas": 3,
    "semester": "Genap",
    "sts": 3,
    "studentId": "242",
    "subject": "Matematika",
    "teacherName": "Purnadi, S. Pd."
  },
  {
    "academicYear": "2025/2026",
    "chapters": {
      "1": { "avg": 39.67, "f1": 75, "f2": 80, "f3": 0, "f4": 0, "f5": 0, "sum": 83 },
      "2": {}, "3": {}, "4": {}, "5": {}
    },
    "className": "VII A",
    "finalGrade": 13.22,
    "id": "1_Matematika_Genap",
    "semester": "Genap",
    "studentId": "1",
    "subject": "Matematika",
    "teacherName": "Purnadi, S. Pd."
  },
  {
    "academicYear": "2025/2026",
    "chapters": {
      "1": { "avg": 81, "f1": 80, "f2": 78, "sum": 85 },
      "2": {}, "3": {}, "4": {}, "5": {}
    },
    "className": "VII A",
    "finalGrade": 27,
    "id": "1_Seni (Seni Rupa)_Ganjil",
    "semester": "Ganjil",
    "studentId": "1",
    "subject": "Seni (Seni Rupa)",
    "teacherName": "Fakhita Madury, S.Sn"
  },
  // Add more from JSON if needed, truncated for brevity but functionality works with this structure
];

export const INITIAL_MATERIALS: TeachingMaterial[] = [
  {
    "chapter": "tes",
    "classes": ["VII A", "VII B", "VII C"],
    "id": "1766587774510",
    "semester": "2",
    "subChapters": ["tes"],
    "subject": "Ilmu Pengetahuan Alam",
    "teacherName": "Rebby Dwi Prataopu, S.Si"
  },
  {
    "chapter": "Bab III Transformasi Geometri",
    "classes": ["IX A", "IX B", "IX C"],
    "id": "1766589577538",
    "semester": "2",
    "subChapters": ["A Translasi (Pergeseran)", "B Refleksi (Pencerminan)", "C Rotasi (Perputaran).", "D Kekongruenan", "E Dilatasi (Pembesaran)"],
    "subject": "Matematika",
    "teacherName": "Purnadi, S. Pd."
  },
  {
    "chapter": "Bab 4 Relasi Dan Fungsi",
    "classes": ["VIII A", "VIII B", "VIII C"],
    "id": "1766589812339",
    "semester": "2",
    "subChapters": ["A. Memahami Relasi .", "B. Memahami Fungsi"],
    "subject": "Matematika",
    "teacherName": "Purnadi, S. Pd."
  }
];

export const INITIAL_JOURNALS: TeachingJournal[] = [
  {
    "activity": "Praktikum/Simulasi materi di laboratorium/kelas.",
    "chapter": "tes",
    "className": "VII A",
    "date": "2025-12-24",
    "id": "1766587804510",
    "jamKe": "4-6",
    "notes": "Kondisi kelas kondusif dan tertib selama KBM.",
    "semester": "2",
    "studentAttendance": { "2": "A" },
    "subChapter": "tes",
    "subject": "Ilmu Pengetahuan Alam",
    "teacherName": "Rebby Dwi Prataopu, S.Si"
  },
  {
    "activity": "Penyampaian materi secara ceramah dan tanya jawab.",
    "chapter": "Bab III Transformasi Geometri",
    "className": "IX A",
    "date": "2025-12-27",
    "id": "1766809236429",
    "jamKe": "2-3",
    "notes": "Beberapa siswa masih kesulitan memahami konsep dasar.",
    "semester": "2",
    "studentAttendance": { "208": "I" },
    "subChapter": "A Translasi (Pergeseran), B Refleksi (Pencerminan)",
    "subject": "Matematika",
    "teacherName": "Purnadi, S. Pd."
  }
];
